### ISSUE TITLE
We need a CI/CD pipeline to a production cloud --AWS, Azure or ...?

### ISSUE THREAD

**Issue by BryanWilhite** [Lambda-Cartel/Nikeza#1]
Continuous integration/deployment anyone? My vote is Azure (but I am biased). I just thought we could track this issue openly and flesh this out: whatever we will build will have to be in a CI/CD pipeline.

**Comment by awright18** [comment]
I second that this, VSTS and Azure is my vote.

**Comment by bizmonger** [comment]
Bryan, can you add a task to the project for this and manage it?

**Comment by BryanWilhite** [comment]
I'm on it.

**Comment by BryanWilhite** [comment]
I've reopened to verify that Ody and Pablo have chimed in...

**Comment by yelluw** [comment]
No issues on my end. This is a great idea. Let's document how to do this as well.

**Comment by BryanWilhite** [comment]
Cool.

Ody will probably see this later tonight my time.

And when it comes to documentation, I will probably go overboard with the markdown files.

Also, Donovan Brown has a some //Build videos on this: https://channel9.msdn.com/Events/Build/2017?sort=status&direction=desc&c=donovan-brown&term=

Specifically: [Build a CI/CD pipeline from Visual Studio Team Services](https://channel9.msdn.com/Events/Build/2017/P4161)

**Comment by awright18** [comment]
@BryanWilhite if you run into any issues, feel free to reach out to me, I'm very familiar with Visual Studio team services.  There should be no problem for all of us having access to this either if we need to. You can have five free users for free.

**Comment by BryanWilhite** [comment]
@awright18 got it...

**Comment by odytrice** [comment]
Yeah me too I'm very Familiar with VSTS. That's what I use at my Day Job. I have lots of experience with it

**Comment by BryanWilhite** [comment]
Hey @bizmonger is the Azure account in place? Is Azure moving or can I get in to Azure and get it moving?

**Comment by bizmonger** [comment]
I haven't done anything with Azure.


By all means, take over.

**Comment by awright18** [comment]
When using azure whomever sets this up can we use a separate subscription,  then all resources can be managed in that subscription and I believe admin rights can be shared at the subscription level,also I will volunteer to be the billing contact/ source for that subscription as I think you can separate that as well.

**Comment by awright18** [comment]
You can have multiple subscriptions tied to a single Microsoft account so any existing Microsoft account should work for this

**Comment by BryanWilhite** [comment]
Ok @awright18 my plan was to establish lambdacartel.visualstudio.com, I am unaware of how to do this with my existing Azure subscription. So do go forward with this.

**Comment by BryanWilhite** [comment]
I am closing this issue and moving it to: https://github.com/Lambda-Cartel/everything/issues/12
