### ISSUE TITLE
Search module

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#10]
As an end-user, I want to discover other developers that provide content on specific topics (i.e. tags), so that I can increase my understanding in specific areas.

**Comment by awright18** [comment]
May be not search specifically but related content scenarios might be a great place for me to start playing with neo4j.  Like shared tags or posts by individuals and things of that nature might be a neat way to do discovery. I'll think about this more and maybe try to come up with interesting scenarios that might make sense.

**Comment by awright18** [comment]
Closing this because I converted the project card to an issue.
