### ISSUE TITLE
WordPress Integration throws unhandled exceptions.

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#100]
WordPress Integration throws unhandled exceptions when invalid arguments are provided.

Todo - Vet parameter values before arbitrarily processing them.

**Comment by yelluw** [comment]
I would honestly rewrite this. It's not built well. Plus its built to process the wordpress feed when the user visits a specific URL. I think the way the wordpress integration should work is to have a cron job running every `n` amount of time and it saves all new content into the database directly.

Let me do a PR to remove the part that ties it into the URL.

related to #53

**Comment by odytrice** [comment]
Looking at merging the Wordpress and Youtube projects into the Main Project as they are effectively a file each

**Comment by bizmonger** [comment]
I deleted the WordPress implementation.
I'll have a new implementation written by end of week.
