### ISSUE TITLE
Using updated database connection string throws exception

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#104]
I am unable to use database connection string.

```
  "ConnectionStrings": {
    "NikezaDb": "Data Source=(local);Initial Catalog=Nikeza;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
  }
```

What changes do I need to make on my end to not use a hardcoded path?

> Failed   Follow
> Error Message:
>  System.Data.SqlClient.SqlException : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found
> or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, erro
> r: 40 - Could not open a connection to SQL Server)
>   ----> System.ComponentModel.Win32Exception : The system cannot find the file specified

**Comment by odytrice** [comment]
Change the connectionstring from 

`Data Source=(local);Initial Catalog=Nikeza;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False`

to

`Data Source=(local)\SQLExpress;Initial Catalog=Nikeza;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False`

**Comment by odytrice** [comment]
I changed it to be able to test it locally (because my sqlserver installation is at the default instance) and forgot to change it back
