### ISSUE TITLE
Need to add Stackoverflow service to integration tests

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#112]
Need to add Stackoverflow service to integration tests

**Comment by bizmonger** [comment]
@marukami Is there a StackOverflow service on Nikeza.Server?

**Comment by mtilbrook-dev** [comment]
Don't think so. You can either use a REST call and get the data from the ExpressJs services, or you can copy the [data.json](https://github.com/Lambda-Cartel/Nikeza/blob/master/Services/Stackoverflow/data.json) with all the tags into the Nikeza.Server and have F# parse it and load it up.

**Comment by bizmonger** [comment]
@marukami  I meant the Stackoverflow service for fetching a "Source"?
Source: Platform + username

**Comment by bizmonger** [comment]
Done.
