### ISSUE TITLE
Judgement Day

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#114]
Deploy Nikeza (_alpha_)

**Comment by odytrice** [comment]
I thought I setup automated build/deployments will verify that.

UPDATE:
For some reason, VSTS doesn't get notified when when push to master. Changed it to Daily Builds/Deployments

Also noticed that yarn is not beign installed and as a result the client build script isn't working
But that has been fixed too

**Comment by odytrice** [comment]
For some reason, VSTS doesn't get notified when when push to master. Changed it to Daily Builds/Deployments

**Comment by bizmonger** [comment]
Done.
