### ISSUE TITLE
Updating wordpress integration

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#131]
## Code is in branch [wordpress-db](https://github.com/yelluw/Nikeza/tree/wordpress-db)

- Removed old integration that passed the parsed XML feed as JSON through route.

- Began adding SQL query strings to insert feed data once processed.

- Began adding functions to insert data into DB.

**Nothing is tested**

## Issues

- Have not been able to connect to MSSQL DB running on docker. Currently seems to be setup for the express version running with the visual studio integration. Maybe @marukami can help?

- RSS feed models still don't feel right.

- Functions that process RSS feed are still not very good and dont handle exceptions.

- Need to add code to call this as a background (cron) job. Guess this is something that depends on azure. @odytrice any ideas?

**Comment by yelluw** [comment]
Have not opened a pull request because its not currently worth it

**Comment by bizmonger** [comment]
I hope to begin work on this on Monday after I finish integrating YouTube on the data sources page.

**Comment by bizmonger** [comment]
I found the url to feed to the wordpress API.

I'll have this implemented by the end of the week.
