### ISSUE TITLE
Contributor module:

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#18]
As a submitter, I want to post content (i.e. article, video, podcast) to Nikeza, so that I can keep track of all my technical contributions to my developer community.

**Comment by bizmonger** [comment]
Mockup provided:

![contributorpage](https://cloud.githubusercontent.com/assets/11041788/26762782/e1257154-4915-11e7-9908-3178c80ccdab.png)

**Comment by bizmonger** [comment]
This is almost complete.
I still need to implement the search feature for this page / module.
After that, I'm prepared to close this out.

**Comment by bizmonger** [comment]
Done.
