### ISSUE TITLE
How to build project

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#2]
@bizmonger ,

To help newcomers and other members, would you document how to build the app? Thanks :)

Could also include how you have VSCode setup? What plug-ins and related settings.

**Comment by bizmonger** [comment]
Okay.




Get Outlook for Android







On Thu, May 25, 2017 at 10:21 PM -0400, "Pablo Rivera" <notifications@github.com> wrote:












@bizmonger ,


To help newcomers and other members, would you document how to build the app? Thanks :)

**Comment by bizmonger** [comment]
Added the installation wiki page to the Everything wiki.

**Comment by bizmonger** [comment]
I'll add the details about the VSCode dependencies in another post soon.

**Comment by yelluw** [comment]
Ok, will leave issue open until then.

**Comment by yelluw** [comment]
Ok, instructions are now perfect. Thanks!

Closing...
