### ISSUE TITLE
Register module:

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#21]
As a developer, I want to use Nikeza as a platform to streamline my professional content from other web sites, so that employers can view all of my contributions using one platform.

**Comment by awright18** [comment]
I have a basic registration api working that just takes username and password, and hashes the password, and stores them in a username.json file.  This is just temporary until we decide on a database technology and if we want to leverage an existing "membership" system or not.

**Comment by bizmonger** [comment]
I completed the client-side registration.
Registration includes:
first name
last name
email
hash-code from password
