### ISSUE TITLE
Videos module:

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#24]
As an end-user, I want to view all videos referencing my favorite developer.

**Comment by bizmonger** [comment]
Current vision for viewing ALL videos of a contributor:

1. On the Home page, the user clicks on contributor thumbnail.
2. The user observes the Contributor page.
3. The user clicks the "more..." link under the videos header.
4. The user observes the Contributor Videos page.

**Comment by bizmonger** [comment]
Done.
