### ISSUE TITLE
Articles module:

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#25]
As an end-user, I want to view all articles provided by my favorite developer.

**Comment by bizmonger** [comment]
Current vision for viewing ALL articles of a contributor:

1. On the Home page, the user clicks on contributor thumbnail.
2. The user observes the Contributor page.
3. The user clicks the "more..." link under the articles header.
4. The user observes the Contributor Articles page.

**Comment by bizmonger** [comment]
Done.
