### ISSUE TITLE
Podcasts module:

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#26]
As an end-user, I want to view all podcasts provided by my favorite developer.

**Comment by bizmonger** [comment]
Current vision for viewing ALL podcasts of a contributor:

1. On the Home page, the user clicks on contributor thumbnail.
2. The user observes the Contributor page.
3. The user clicks the "more..." link under the podcasts header.
4. The user observes the Contributor Podcasts page.

**Comment by bizmonger** [comment]
Done.
