### ISSUE TITLE
Need access to view build status

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#30]
https://lambdacartel.visualstudio.com/Nikeza/_build

> 401 
> Not Authorized
> Sorry, but Scott Nimrod <scott.nimrod@bizmonger.net> (Microsoft account) is not authorized to access this page
> Sign out and connect with another login  
> Service Status and Support @VSTeam 
> More information about this error
> TF400813: The user 'Windows Live ID\scott.nimrod@bizmonger.net' is not authorized to access this resource.

**Comment by BryanWilhite** [comment]
@bizmonger, @awright18 I am getting the same not authorized message. ...had no idea that you guys went ahead with Azure :|

**Comment by awright18** [comment]
I didn't set this up either, I think it may have been @odytrice

**Comment by odytrice** [comment]
Sorry, Adding now. I added Bizmonger@gmail.com

**Comment by BryanWilhite** [comment]
@odytrice is my email in there? (bryan.wilhite at gmail)

**Comment by odytrice** [comment]
will add the emails

**Comment by BryanWilhite** [comment]
@odytrice sorry i gave you the wrong email -please discard the previous and use rasx at songhaysystem.com

**Comment by bizmonger** [comment]
Closing this due to no one acting on this as a priority.
