### ISSUE TITLE
Automate creation of links to content via WordPress API

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#32]
As a Contributor, I want Nikeza to find my articles on WordPress so that I do not have to manually create links to all of my articles hosted on WordPress.

1. Provide userid to WordPress' web services
2. Package (i.e. tags, title, description, link) post for client app to consume.

**Comment by awright18** [comment]
thinking this might be able to use RSS for this.

**Comment by yelluw** [comment]
Found this Elm lib to parse RSS (XML) https://github.com/stkb/elm-xml-parser

**Comment by bizmonger** [comment]
We need to filter and attach the tags that are attached to a WordPress article are found in the StackOverflow tags when a user specifies a source for his/her links.

**Comment by bizmonger** [comment]
Done.
