### ISSUE TITLE
Automate creation of links to videos via YouTube API

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#33]
As a Contributor, I want Nikeza to find my videos on YouTube so that I do not have to manually create links to all of my videos hosted on YouTube.

1. Provide userid to YouTube's web services
2. Package (i.e. tags, title, description, etc) video posts for client app to consume.

**Comment by mtilbrook-dev** [comment]
There is a data API that should work. https://developers.google.com/youtube/v3/getting-started

I can give this one a crack.

**Comment by mtilbrook-dev** [comment]
Next thing would be to add unit tests to the library.

**Comment by mtilbrook-dev** [comment]
Quick status update. Been busy with work this week. I'll have time this weekend to look at using either [hedgehog](https://github.com/hedgehogqa/fsharp-hedgehog) or [FsCheck](https://github.com/fscheck/FsCheck)

**Comment by bizmonger** [comment]
I did a presentation on FSCheck.
I also have hella blog posts on the topic.

**Comment by mtilbrook-dev** [comment]
Would you be willing to do a recorded pair program session?

**Comment by bizmonger** [comment]
FsCheck: https://youtu.be/56E8qV9vcSE
I was still learning F# at the time. So I said some things wrong.

Blog Posts:
https://bizmonger.wordpress.com/?s=FsCheck

**Comment by mtilbrook-dev** [comment]
Looking at the YouTube Data API docs. I think It should be possible to allow the user to authorize Nikeza to access their YouTube data with OAuth. 

Otherwise, we can still use the existing code and use either a `username` or `channelId`

**Comment by bizmonger** [comment]
What's the status on this?
Can I close this ticket?

**Comment by mtilbrook-dev** [comment]
It works. You do need a google app API key before you can call it the end point on the server, but it works. 

Yes, I think we can close this issue. Adding OAuth access can be done later in another ticket.
