### ISSUE TITLE
Import tags from StackOverflow

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#36]
As a maintainer, I want to prevent duplication of topics within the system so that users can appropriately link their content to constrained topics and that users can easily search for unique topics.

**Example:** 
(Wpf , Windows-Presentation-Foundation) 
(Elm , Elm-lang)

"Software Development", "Programming", and "Web Development" are too broad of subjects for filtering to be useful. Instead, topics such as "Craftsmanship" or "Clean-code", "Continuous Deployment", "Continuous Integration", "Web Design", "Xamarin.Forms", "Property-based Testing" are more helpful for filtering topics.

**Objective:**
Integrate with StackOverflow's API to pull down the curated tags for Nikeza to import into its system.

**Comment by mtilbrook-dev** [comment]
I can get this one a go. 

I'll probably use https://facebook.github.io/reason/ to write a microservice.

- [/tags](https://api.stackexchange.com/docs/tags#order=desc&sort=popular&filter=default&site=stackoverflow&run=true) Returns the tags found on a site.
- [/users/{ids}/badges](https://api.stackexchange.com/docs/badges-on-users#order=desc&sort=rank&ids=22656&filter=default&site=stackoverflow&run=true) Get the badges the users in {ids} have earned.

**Comment by mtilbrook-dev** [comment]
I got a simple rest call [working in Reason ](https://github.com/Lambda-Cartel/Nikeza/tree/overflow) next I'm going use [Reason Express](https://github.com/BuckleTypes/bs-express) bindings to create a service we can call as much as we want to get stackoverflow tags.

**Comment by bizmonger** [comment]
@marukami 
I assumed this can be closed now.
