### ISSUE TITLE
Strategy for F# Backend Codebase

### ISSUE THREAD

**Issue by odytrice** [Lambda-Cartel/Nikeza#4]
How should we do the back-end? Do we have it as separate folder in the Repository or create it's own repository?

Here are the pros and cons of having a separate project
### Pros 
- It can have its own Issues and pull-requests etc
- Separates the Font-End and Back-End Concerns

### Cons
- Yet another project to manage
- Coordinating changes in the "Rest Interface" across project might be a bit of a challenge

**Comment by awright18** [comment]
I guess the question is are we going to deploy things separately? Are we going to host an API and an elm app in the same applications?

**Comment by awright18** [comment]
Also, not sure if you guys have heard of Giraffe. Its the next generation of suave.io, built specifically on top of .NET Core to leverage all the things the Asp.NET team has done, but let you do things in an F# way of course.  I have yet to play with it, but I think learning is one of our goals, I'd suggest we check it out.   I'd love thoughts from others.

**Comment by bizmonger** [comment]
I currently lean on the side of creating a separate folder for the backend (aka: server). Hence, maintaining the backend on the same project.
In fact, I'm leaning really hard towards that approach.

Is that okay?

**Comment by awright18** [comment]
I think that is perfectly fine, especially if they will be deployed on the same machine at the same time. That makes that a bit easier.

**Comment by odytrice** [comment]
Okay, project folder it is then

**Comment by odytrice** [comment]
@awright18 I also had giraffe in mind too.

Here is the thing with .NET Core. Its ready for prime time and in fact I have like 3 critical projects in production that are running on it.

The F# tooling is on par with C# the only snag is that there is no support for Visual Studio yet which I assume is not a big deal for us. and...

Type Providers don't work yet because of some missing APIs into DotNet Core Runtime.

The current work around would be to use ASP.NET Core and the DotNet CLI to target the Mono (which also runs on Windows btw).

Another option is to target Mono directly using tools like Fake to build the application

If we decide to use F# I'm strongly in favor to using .NET Core as we'd be future proofing our solutions

**Comment by yelluw** [comment]
Yes, mono repo, please. Simpler to manage. No need for micro-services at the moment (those come at scale).

@odytrice Could F# with core be written using Visual Studio Code ?

**Comment by yelluw** [comment]
Looking at Ionide which allows writing F# on visual studio code on any OS.

**Comment by mtilbrook-dev** [comment]
I agree with a mono repo. 

I only have MacOS. I've used [ionide](http://ionide.io/) with .NETCore with Visual Studio Code without any major issues. [Visual Studio for Mac](https://www.visualstudio.com/vs/visual-studio-mac/) also work pretty well, I mostly use Ionide.

**Comment by odytrice** [comment]
@yelluw Visual Studio code is the default for F# running on .NET Core. Visual Studio support is in the pipeline.

@marukami The only issue I have with using the regular Mono is that FSProj is a nightmare to edit especially with the whole Binding Redirects headache. The .NET Core F# workflow is a much more streamlined experience

**Comment by mtilbrook-dev** [comment]
@odytrice sorry that was grammatically ambiguous of me. By Mono repo, I was talking about the git repository pattern https://developer.atlassian.com/blog/2015/10/monorepos-in-git/ 
If you are referring to Mono as the runtime. Then, yes I agree .NET Core workflow is much better.

**Comment by odytrice** [comment]
Oh I see.. Thanks for the link. Learnt something useful.

**Comment by odytrice** [comment]
@bizmonger Where do we put the Server side stuff? Do we have two folders for the corresponding code bases? As in Client and Server, Such that everything we currently have in the repository will be under a client folder?

**Comment by bizmonger** [comment]
Sounds good to me.

**Comment by odytrice** [comment]
aiight cool

**Comment by yelluw** [comment]
Just following up:

- We are going with giraffe

**Comment by yelluw** [comment]
#### Let's talk databases

I assume others will gravitate towards MSSQL, but I'm not sure if that fits our needs well.

I have experience with PostgreSQL and its a mighty fine DB. Stable, FOSS, and lots of useful features (like storing and querying JSON).

Input? 🙏

**Comment by bizmonger** [comment]
My comfort zone is SQL Server for the database.
I'm open to NoSQL for image files or documents.

**Comment by mtilbrook-dev** [comment]
I would still no use. NoSQL for blob storage. If we need a file store I
would look at S3 or Azure blob storage.

Mssql added JSON support in 2016.

Otherwise there is the Azure document store if you want to use a document
NoSQL database.

I would start with mssql and the expand as needed.

**Comment by awright18** [comment]
So an example if we are starting out in Azure we could get the app hosted (shared hosting) with a 2GB sql server instance for about $15 a month. If we can do PostgreSQL on another platform and host the site for less I think its worth considering. 

You probably shouldn't store image files in a database.  CDN will work for that. You can absolutely store the url to image files in a database,  Document dbs usually store JSON objects.  Actual documents like pdfs etc would also be stored on a CDN.

**Comment by bizmonger** [comment]
So have we decided on the technologies to close this issue out?

**Comment by odytrice** [comment]
Yeah, Closing now
