### ISSUE TITLE
Flesh out features

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#5]
I noticed in the features Project there are a bunch of high level modules, but there isn't any descriptions.  One thing you can do with projects is add Issues to them. Issues can be tagged as features, and often are.  Creating this as issues would also allow multiple people to discuss/understand what the goal of each feature is and allow us to start working on them.

**Comment by bizmonger** [comment]
Yea... I purposely left it abstract for the modules to be open to interpretation and discussion. Thanks for calling it out.






On Sun, May 28, 2017 at 10:05 AM -0400, "Adam Wright" <notifications@github.com> wrote:












I noticed in the features Project there are a bunch of high level modules, but there isn't any descriptions.  One thing you can do with projects is add Issues to them. Issues can be tagged as features, and often are.  Creating this as issues would also allow multiple people to discuss/understand what the goal of each feature is and allow us to start working on them.

**Comment by yelluw** [comment]
We should define a spec for the project. Im itching to jump in and code but feel a bit lost not having something to work towards to. :)

**Comment by yelluw** [comment]
Related to #7

**Comment by bizmonger** [comment]
Features have been described via "Open Issues"
