### ISSUE TITLE
Adding style

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#52]
I've gone ahead and submitted a pull request to use the Bootstrap framework to make dealing with the UI a bit easier. That doesn't change much in terms of the basic template. However, using the bootstrap components such as forms and the like does require additional elm code to be written (from what Ive  gathered on my research).

Opinions are welcome.

**Comment by bizmonger** [comment]
Can I close this?
I added some basic alignments to the pages via CSS.

**Comment by yelluw** [comment]
If you accept the pull request the changes you made will be overwritten

**Comment by bizmonger** [comment]
I don't want to accept the pull request then.
