### ISSUE TITLE
Read RSS feed from wordpress blog

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#53]
Im working on a small library/package that will allow us to read the RSS feed of a wordpress blog to then show it on the UI.

Reading the feed on the client side reduces the backend load. It also limits how much data we need to store on a backend DB. All that would be needed is the RSS feed URL which is standard in wordpress.

This would then be used to populate things as the current design calls for.

**Comment by yelluw** [comment]
related to #32

**Comment by yelluw** [comment]
Note that this functionality was moved to the backend.

cc @awright18

**Comment by bizmonger** [comment]
What's the status on this?
Can this be closed?
