### ISSUE TITLE
Key Stores

### ISSUE THREAD

**Issue by mtilbrook-dev** [Lambda-Cartel/Nikeza#58]
It would be good to have a "key stores" for storing API keys and secrets.

- https://www.vaultproject.io/
- https://azure.microsoft.com/en-au/services/key-vault/

**Comment by bizmonger** [comment]
Preferably Microsoft. 
Hence, their brand is on the line.

**Comment by awright18** [comment]
There is a data protection API built into Asp.net core.  It has built in support for blob storage, but I think we could probably build or find an implementation for azure key vault.

**Comment by mtilbrook-dev** [comment]
A few people seem to want the Azure key. So, let's go with Azure here. 

@awright18 The Azure key vault has both Java and dotNet client SDK's, and a rest API. https://docs.microsoft.com/en-au/azure/key-vault/ We maybe need a thin wrapping for F#

**Comment by bizmonger** [comment]
Done.
