### ISSUE TITLE
Navigation button ignores specified style after being clicked

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#59]
Navigation button ignores specified style after being clicked.

Steps:
1. Register or login to Nikeza.
2. Observe navigation pane.
3. Click on a navigation button.
4. Observe clicked button returns to default style (i.e. color, height, width)

Expected:
Button should retain style defined in CSS file after being clicked.

**Comment by yelluw** [comment]
Adding some info to the issue. These are the buttons with the bug:

![screen shot 2017-06-26 at 9 56 46 pm](https://user-images.githubusercontent.com/23017027/27567542-6f5e40ee-5aba-11e7-8a11-b498f31f055d.png)
![screen shot 2017-06-26 at 9 56 52 pm](https://user-images.githubusercontent.com/23017027/27567543-6f608fac-5aba-11e7-8880-fa822fcd51ed.png)

When clicked the style is lost. Working on this... :)

**Comment by yelluw** [comment]
@bizmonger Added pull request with fix. 😀

**Comment by yelluw** [comment]
Closing since it was merged.
