### ISSUE TITLE
Trello Issue board

### ISSUE THREAD

**Issue by mtilbrook-dev** [Lambda-Cartel/Nikeza#6]
The GitHub project is alright it's a bit hard to have a conversation about a task. Would making a Trello work better. Looking at http://blog.trello.com/github-and-trello-integrate-your-commits you can link issues to Trello. Then we can sort and kanban board issue in Trello. Thoughts?

**Comment by yelluw** [comment]
I personally prefer to use github projects but with issues and not notes. It ends up being similar to Trello.
Good idea to explore options. Let's see what others think. :)

**Comment by awright18** [comment]
I agree with @yelluw while trello is cool its just another site to manage. Projects seems to be a good idea.

**Comment by odytrice** [comment]
I'm in favor of Projects. Trello is a great product but Github Projects does basically the same thing

**Comment by awright18** [comment]
We should attach the issues to the projects though in my opinion instead of rogue cards. This is exactly the use case @marukami was wanting.

**Comment by yelluw** [comment]
I consider this to be resolved. Thanks to everyone involved and specially to @marukami for providing ideas. :)
