### ISSUE TITLE
Style Home page's "Join" section

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#60]
Style the Home page's "Join" section so that it screams value.

**Comment by yelluw** [comment]
@bizmonger 

## Do you mean the Join button depicted below?

![screen shot 2017-06-26 at 10 11 43 pm](https://user-images.githubusercontent.com/23017027/27567853-70a32d32-5abc-11e7-8f43-1249a96ea034.png)


## Or the signup / join page with the form?

![screen shot 2017-06-26 at 10 12 21 pm](https://user-images.githubusercontent.com/23017027/27567871-89fcccac-5abc-11e7-9cb3-efdb19517704.png)

**Comment by bizmonger** [comment]
I meant on the Home page.
But the registration page can be touched up as well.

**Comment by yelluw** [comment]
Got it. Will work on it.

**Comment by yelluw** [comment]
Coming back to this now that wordpress pull request is pending.

**Comment by bizmonger** [comment]
Evolved to being no longer necessary.
