### ISSUE TITLE
Open Nikeza up to other interests

### ISSUE THREAD

**Issue by bizmonger** [Lambda-Cartel/Nikeza#63]
As a woman, I want to subscribe to topics from my favorite beauty experts so that I can learn about and try different hair styles and makeup.

As a self-improvement junkie, I want to subscribe to John Sonmez, and Tony Robbins so I can catch their latest videos, blog posts, and podcasts.

**Note:**
_Nikeza_ can accelerate its adoption by focusing on several interests instead of just one.
Thus, this will increase visibility and bring in experts from different industries for their followers to subscribe to on this platform.

Update the EditProfile page of a user so that they can select their interests.
When updated, the Search box's auto suggest will filter topics based on the user's profile.

**Interests**
Expand _Interests_ to the following:
* Software Development
* Beauty & Cosmetics
* Self Improvement
* Dating

**Comment by yelluw** [comment]
I think this will be doable to a certain extent as is. RSS subscriptions dont care about topics. They are dumb feeds.

I do disagree with trying to be everything to everyone. It's simpler to focus on one target group (ourselves) and do the best possible.

**Comment by bizmonger** [comment]
I beg to differ.
The UI is still agnostic to _field of interest_.

> "Linking your expertise"

 The above slogan isn't just for software development.
It's for professionals that have content across the World Wide Web.

In fact, StackOverflow demonstrated that their platform is useful for other communities including (chemistry, astronomy, foreign languages, etc.)

Note that no changes are made to any of the user interfaces at all with the only exception being that of the user Profile page.

The user profile page will provide a check list of interests that a user can perform a search on.

Once interests are specified, the home page will refresh with recommended content providers based on the user's interests that is drawn from the user's Profile page.

**Comment by bizmonger** [comment]
Added Interests table.
Defaulted to Software Development for now.

Todo: Wire up profile registration to software development interest.
