### ISSUE TITLE
Backend development setup

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#64]
@awright18 @odytrice @marukami 

#### Disclaimer: I am not well versed in .NET tech. Be patient. :)

I want to start working on the backend and need help setting up my development environment.

My machine is a Mac. I have a windows 10 VM with VS2015 available as well (I do prefer OSX).

What do I need to install in order to get started.

Please use step by step instructions. :)

**Comment by bizmonger** [comment]
[F# Productivity Power Tools](https://fsprojects.github.io/VisualFSharpPowerTools/)

[F# SQL Type Provider](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/type-providers/accessing-a-sql-database)


[SQL Server Management Studio](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms)

[REPL](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/fsharp-interactive/)

**Comment by yelluw** [comment]
Is this for windows or mac ? ☺

**Comment by yelluw** [comment]
Note that the abive are for windows.

**Comment by awright18** [comment]
[Visual Studio Code](http://code.visualstudio.com)
[dot.net](https://www.microsoft.com/net/download/core) grab the .NET Core SDK not the runtime
[ionide] https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp
[postman] https://app.getpostman.com/app/download/osx64 --for calling apis 
1. pull down the repo
2. navigate to Server/Nikeza.Server  
3. open VS Code
4. open the terminal by clicking CMD + ` 
5. type dotnet restore
6. hit enter
7. type dotnet run 
8. ask for help with hitting the apis.

**Comment by mtilbrook-dev** [comment]
@awright18 I think you mean ``Control + ` ``
``CMD + ` ``  switches between specific application windows 

I only have Mac's as well. @awright18 setup guide above worked fine. You will need to install [DotNetCore](https://www.microsoft.com/net/core#macos) if you haven't already.

I'll document the setup and run in a README.md

**Comment by yelluw** [comment]
@awright18 @marukami 

I looked into postman and seems I can instead use cURL (which is what I normally use to talk to APIs).
Any specific reason (outside of having a GUI) I should use it? :)

**Comment by yelluw** [comment]
Note:

- Had to update `openssl` by using `homebrew`

`brew update`   <-- Update the package listings for homebrew
`brew install openssl`   <-- install the latest openssl package listed
`brew link --force openssl`  <-- make the homebrew installed version the default
`openssl version -a`  <-- view the version to confirm the update

**Comment by yelluw** [comment]
- [x] VS Code updated to latest stable version

- [x] .NET Core SDK installed

- [x] OpenSSL updated to latest stable

- [x] Ionide installed

**Comment by yelluw** [comment]
.NET core has telemetry...

To opt out of it run the following bash command:

`echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" | sudo tee -a /etc/environment`

**Comment by yelluw** [comment]
It's officially running

![screen shot 2017-06-27 at 10 33 30 pm](https://user-images.githubusercontent.com/23017027/27618157-aacd40d4-5b88-11e7-97aa-6a753b3b0961.png)


Thanks to everyone. I will clean up the instructions and add them to the wiki.

**Comment by mtilbrook-dev** [comment]
I'm pretty sure postman can save collections of API calls that you can run in sequence. I'm pretty sure you can also setup teams and share the saved API call definition.

**Comment by yelluw** [comment]
Good points.

Is there a lambda cartel postman team account or something similar?

**Comment by mtilbrook-dev** [comment]
Looks like postman charges $8/user for the sharing. The other option is to use git to share the JSON files postman exports.

**Comment by yelluw** [comment]
We could put them in a new directory at the project root. Then it would be:

`/Client`
`/Server`
`/Postman`

What do you think?

**Comment by mtilbrook-dev** [comment]
Looks good.

**Comment by yelluw** [comment]
Ok, then I propose we use that convention.

@awright18 @odytrice do you agree?

**Comment by awright18** [comment]
Maybe just unit tests would be better, but I'm not against also putting example requests some where in there.

**Comment by yelluw** [comment]
Closing this one and putting the data into the wiki
