### ISSUE TITLE
Docker Dev Environment 

### ISSUE THREAD

**Issue by mtilbrook-dev** [Lambda-Cartel/Nikeza#65]
At my last role, we used Docker to manage the dev environment. Docker allowed anyone to get started by simply getting Docker and starting the Docker cluster; The cluster was simple a YAML file that started a single instance of each service.

We need an image for, 
[] - Client/Server
[] - Database

Finally, a `Docker compose` file to start a cluster that contains all the services and watch the host src directories for changes and recompiles as needed.

**Comment by yelluw** [comment]
Yes, i was thinking of this today. Makes things simpler.

What do you think would be a good way to do this? 😀

**Comment by mtilbrook-dev** [comment]
1. Setup a Lambda-cartel [docker hub](https://hub.docker.com/) account
2. Create images for each service
3. Submit each image to the docker hub account 
4. Create a Docker folder in the project root and use [Docker Compose](https://docs.docker.com/compose/overview/) to manage a environment

Docker hub takes ~10min to compile and distabute updates to an Image. I would suggest mounting any files that change often instead of embeded them into the image.

**Comment by awright18** [comment]
Client and server a likely going to be apart of the same application.  At this time we won't be making a distinction between them. It'll be easy to pull apart if there is that need though later.  So I think one image for the App itself (including client-server) is fine and a separate one for a development time database is fine too.

**Comment by mtilbrook-dev** [comment]
That makes sense. I'll move the Docker for Client up into the Docker folder.

**Comment by bizmonger** [comment]
Removing Docker as a result of it not being used or maintained.
