### ISSUE TITLE
Auth Platform

### ISSUE THREAD

**Issue by mtilbrook-dev** [Lambda-Cartel/Nikeza#7]
Is the intent to create our own User Authentication or does it make sense to use something like [Auth0](https://auth0.com/) or even look at what Azure can provide?

**Comment by yelluw** [comment]
Nothing has been decided. Having users being able to authenticate with github or google seems like a good option even if we implement our own. Lets define a design doc around this.

**Comment by bizmonger** [comment]
Closing.
This is public info on the web.
