### ISSUE TITLE
Server-Side Testing Framework

### ISSUE THREAD

**Issue by odytrice** [Lambda-Cartel/Nikeza#71]
Following our discussion on [EP006 - Arguing About Unit Testing And Talking About Hiring](https://soundcloud.com/lambda-cartel/ep006-arguing-about-unit-testing-and-talking-about-hiring)

What server-side testing framework to use? Here are a few candidates

- NUnit
- Expecto
- XUnit

@marukami @bizmonger @awright18 @yelluw

**Comment by awright18** [comment]
xunit is fully supported on .net core, expecting isn't yet as far as I can tell. So I'd say let's start with xunit.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by odytrice** [comment]
Expecto is supported on dotnet core https://github.com/MNie/Expecto.Template The only difference is that instead of using `dotnet test` you'd use `dotnet run` instead. This may be a cause a bit of a challenge for setting up build pipelines but there are easy work arounds

**Comment by awright18** [comment]
I'm sorry my research was poor.  I think expecto makes sense since it works with .net core.  Curious why

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by awright18** [comment]
Curious what it would take to make dotnet test work but using a console app isn't a big deal

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by odytrice** [comment]
I'm not sure but I think the reason they picked `dotnet run` rather than `dotnet test` is because they want you to be able to configure the "main" method of your test suite. To be able to add rules for which tests should be run and which should be skipped and other stuff like that. The work around for a build pipeline would be to run it as a batch/shell script and fail on standard out
