### ISSUE TITLE
Dev time build/run/debug on Windows/macOS/Ubuntu with Docker

### ISSUE THREAD

**Issue by awright18** [Lambda-Cartel/Nikeza#72]
I think we need to support building on any platform.   Primarily because we expect to be able to develop on any OS. We should do this by leveraging docker. I have been thinking about this for several days, but haven't had the time to implement it. 

We need to build a container with node and whatever else on top of microsoft/aspnetcore-build. 
This container should have all the tools to build the client and server and run and debug it.

Then we'll need to build a production one on top of Microsoft/aspnetcore. 
This will just need to run Nikeza.Server.  Node is not required. 

The Server app will serve the client code. I think some people may be confused by that.  Elm generates an Html file. Nikeza.Server will server that html file as well as some others.

**Comment by yelluw** [comment]
Good thoughts. Agreed.

**Comment by awright18** [comment]
I need to get this finished, and write some docs for it. I watched the recent "deploying to production" video and seemed like there were some issues with docker.  I'll finish watching the video soon. I'll try to get this done in the next few days.

**Comment by odytrice** [comment]
Yeah that would be awesome. The docker image I built was empty.
