### ISSUE TITLE
Xml CDATA and other items not being deserialized into json

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#74]
@bizmonger 

The code is here: https://github.com/yelluw/fsharprss/tree/master/fsharprss

### Summary:

The CDATA and pudDate (published date) elements in the XML show up as `null` or `"pubDate":{"Case":"Some","Fields":[null]}` when converted to json.

---
The code above gets the rss feed from my blog and turns it into json. The problem is that XML sections labeled as CDATA are not being converted into json.

This is an issue because some of the CDATA fields might be needed in the Nikeza front end. Things like author, pubDate, etc may be useful to have.

**Comment by bizmonger** [comment]
I saw this [link](https://stackoverflow.com/questions/9919593/parse-xml-response-text-having-cdata-in-c-sharp).

**Comment by yelluw** [comment]
Ok, I'm still stuck. :)

I will integrate this code into the server and then work on fixing it. That way we can move forward with the front end integration. I might be trying to get all the fields from the XML and they might not be needed.

Code is on branch `WordpressBuildError` on https://github.com/yelluw/Nikeza

@awright18

**Comment by mtilbrook-dev** [comment]
@yelluw Did you still need help with this?
