### ISSUE TITLE
We need to add an open source license.

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#78]
I suggest the GPL 2.0, because it's what I tend to use. What do you think?

**Comment by yelluw** [comment]
We discussed this yesterday. Here is what's proposed:

- Add dual licenses. One open source license for code and one closed sourced license for commercial usage.

- Add license for for assets (logo, branding)

**Comment by yelluw** [comment]
### Scenarios

Free usage. This means individuals may use the software as long as there is no direct or indirect revenue generated from doing so. 

Commercial usage. Any usage of Nikeza that results in generating revenue. Includes adding advertisements, selling placements, etc.

### Licenses

- GPL V2.0 for free open source usage. As long as there is no revenue generated.

- Paid license to remove restrictions on profit making endeavors using the software. Wording can be as simple as: Copyright `whatever` 2017. To use this software commercially you have to purchase a license. Commercial usage is defined as any type of usage that generates revenue through the use of the software in a direct or indirect manner.

### Branding and assets

For open source license the [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) license fits well (read the license).

For closed source all brand assets are `copyright` their respective owners. By respective owners, I mean those who paid to have the assets designed for the project.



Questions? Suggestions?

@bizmonger

**Comment by bizmonger** [comment]
Sounds good. Can you complete it or do I need to learn how to do this?

**Comment by yelluw** [comment]
I'll finish it. Was making sure it was what we agreed on.

**Comment by yelluw** [comment]
Leaving this for a bit later. Focusing on code now.

**Comment by bizmonger** [comment]
No longer relevant.
