### ISSUE TITLE
Index view details

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#82]
@awright18 

I was talking to @bizmonger yesterday and seems we are ready to start connecting the front end to the backend. This means we have to serve the front end code (html, css, and js files). I dont think we have to move the `Client` directory into the `Server` directory. It might be possible to have Elm generate the JS files and output it to the `Server` directory. Either way, we need to include these files in the `Nikeza.Server` directory.

## Why?

All single page apps (SPA) need an entry point (a moment when the server sends the web browser all of the front end files it needs to run the app).

To us this means we need to have a Controller that serves the index View that returns / renders the file [home.html](https://github.com/Lambda-Cartel/Nikeza/blob/master/Client/app/index.html)

Then we need to make sure that all the JS files generated by Elm are accessible in the wwwroot directory or some other directory where static files would be served.

**Comment by awright18** [comment]
Ok, I think we are on the same page. Yes the server will serve home.html (generated from home.elm). My current dockerfile will build the client, output home.html to the correct location in the server project and serve it appropriately. The JS is included in the page. Unless you have external JS that you are calling like bootstrap etc.

**Comment by awright18** [comment]
I haven't sent that pull request yet. I think it may need some more work but I guess we could get it in the project and update it later

**Comment by yelluw** [comment]
Great. Can you link to the commit/branch?

**Comment by awright18** [comment]
https://github.com/awright18/Nikeza/commit/9855315aba406e6183c1d439df4aeb4cee3586fa

**Comment by yelluw** [comment]
Perfect. It looks like it will do for now. Ill test it on my end and then we can merge it in. Means we probably need to show/document others how to build it. No big deal. I can do that.

**Comment by yelluw** [comment]
Thanks Adam! 👍

**Comment by yelluw** [comment]
@awright18 Could you push this code to a new branch in the main Nikeza repo? Thanks :)

**Comment by bizmonger** [comment]
Haven't reviewed it. But I merged it a couple of minutes ago.

**Comment by yelluw** [comment]
@bizmonger Could you point to what branch it was merged into? :)

**Comment by bizmonger** [comment]
Master

**Comment by yelluw** [comment]
@bizmonger The code Im talking about in this thread is not the one that was merged. :)

I'll clone @awright18 fork ang merge it into mine. 

**Update**

Pulled Adam's code and merging locally (fixing clonficts). 

Thanks all for the help :)
