### ISSUE TITLE
Visual Design

### ISSUE THREAD

**Issue by mtilbrook-dev** [Lambda-Cartel/Nikeza#91]
I'm not a very experienced designer. I was thinking something like https://www.uplabs.com/posts/profile-redesign as an inspiration for a visual guide.

Is anyone experienced with some kind of design tools?

**Comment by yelluw** [comment]
I use Inskscape to prototype stuff, but nothing else aside form that. We can borrow some inspiration from that place. The layout seems fairly straightforward and doable with Bootstrap.

**Comment by yelluw** [comment]
The more I think about this the more I feel we should approach this from a mobile first angle. I think most people would use nikeza on mobile.

By mobile I mean a website that is designed for mobile phones in mind (and desktop too).

**Comment by mtilbrook-dev** [comment]
by using bootstrap would make the design mobile friendly is a lot simpler. Just start with the mobile perspective and work backward to the desktop layout. Up-labs is ideal for design inspirations. 

Yes, mobile phones in mind and doing their design first is ideal.

**Comment by bizmonger** [comment]
Or a Xamarin.Forms with F# app can be built with new link notifications.
Development can be start now.

**Comment by mtilbrook-dev** [comment]
@bizmonger Are you suggesting we stop working on the web client, or that we also start a native mobile client.

**Comment by bizmonger** [comment]
Added Nikeza.mobile folder for mobile users.
