### ISSUE TITLE
Docker Scripts don't work on Windows

### ISSUE THREAD

**Issue by odytrice** [Lambda-Cartel/Nikeza#92]
The current Scripts don't work on Windows e.g. `./docker-build-dev` that's because windows doesn't like files that don't have extensions. and as such doesn't run them.

**Comment by mtilbrook-dev** [comment]
Yep. #93 also broken them. Docker does not accept relative pathing and the scripts need to be updated to get the absolute paths.

You should be able to use Ubuntu on Windows to run the scripts. You need to proxy to the windows docker client; I'll find the article that talked about how you can do this at some point.

I've been looking at using nodejs to create a CLI tool. The [Commander JS](https://github.com/tj/commander.js) library makes it easy to create CLI programs. Then we can create a bash and shell wrapper to make calling the CLI simpler.

**Comment by mtilbrook-dev** [comment]
OK, I fixed the scripts on Unix. I think node will make it simpler to create a simpler CLI with greater flexibility.

**Comment by odytrice** [comment]
Nice. Was wondering if we could use some cross plat build system instead something like Fake or Gulp

**Comment by bizmonger** [comment]
Removing docker scripts from solution as a result of docker no longer being used nor maintained.
