### ISSUE TITLE
Provide access to azure

### ISSUE THREAD

**Issue by yelluw** [Lambda-Cartel/Nikeza#97]
@odytrice could you show us how to push to the azure website? I'm itching to fix the issue we have and continue pushing.

:)

**Comment by odytrice** [comment]
Oh okay. You can just trigger a build from VSTS and it will get into Azure

**Comment by yelluw** [comment]
Cool. When could we figure out the issue we had with it not working on azure the other day? :)

**Comment by odytrice** [comment]
Figured it out. It had to do with IISIntegration package details here #105
